include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.freezed.dart'
    - 'example/lib/**'
    - 'test/.test_coverage.dart'
  errors:
    include_file_not_found: ignore