include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.freezed.dart'
    - 'example/lib/**'
    - 'test/.test_coverage.dart'
  errors:
    avoid_catching_errors: ignore
    include_file_not_found: ignore
    invalid_annotation_target: ignore