name: common_bloc
description: A collection of common blocs and cubits that maybe will be used very often (powered by the bloc library).
version: 3.0.2
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^6.1.0
  dio: ^3.0.10
  freezed_annotation: ^0.12.0
  meta: ^1.2.3
  webfeed: ^0.6.0

dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: ^1.10.4
  effective_dart: ^1.3.0
  freezed: ^0.12.2
  test: ^1.15.5
  test_coverage: ^0.5.0

dependency_overrides:
  analyzer: '0.40.4'
