name: common_bloc
description: A collection of common blocs that maybe will be used very often (powered by the bloc library).
version: 2.0.0
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^4.0.0
  dio: ^3.0.9
  freezed_annotation: ^0.7.1
  meta: ^1.1.8
  webfeed: ^0.4.2

dev_dependencies:
  bloc_test: ^5.1.0
  build_runner: ^1.9.0
  effective_dart: ^1.2.1
  freezed: ^0.10.8
  test: ^1.14.3
