name: common_bloc
description: A collection of common blocs that maybe will be used very often (powered by the bloc library).
version: 2.0.3
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^6.0.1
  dio: ^3.0.9
  freezed_annotation: ^0.11.0
  meta: ^1.2.2
  webfeed: ^0.4.2

dev_dependencies:
  bloc_test: ^7.0.0
  build_runner: ^1.10.0
  effective_dart: ^1.2.4
  freezed: ^0.11.4
  test: ^1.15.3
  test_coverage: ^0.4.3
