name: common_bloc
description: A collection of common blocs and cubits that maybe will be used very often (powered by the bloc library).
version: 4.2.2
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  webfeed: ^0.7.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  coverage: ^1.3.2
  freezed: ^2.0.3+1
  test: ^1.21.1
  very_good_analysis: ^3.0.0
