name: common_bloc
description: A collection of common blocs and cubits that maybe will be used very often (powered by the bloc library).
version: 4.0.0
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  dart_rss: ^2.0.0
  dio: ^4.0.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  bloc_test: ^8.0.0
  build_runner: ^1.12.2
  coverage: ^1.0.2
  freezed: ^0.14.1+1
  test: ^1.16.8
  very_good_analysis: ^2.0.0
