name: common_bloc
description: A collection of common blocs and cubits that maybe will be used very often (powered by the bloc library).
version: 4.0.0-nullsafety.1
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0-nullsafety.3
  dio: ^4.0.0-beta6
  freezed_annotation: ^0.14.0

dev_dependencies:
  bloc_test: ^8.0.0-nullsafety.2
  build_runner: ^1.11.5
  coverage: ^1.0.1
  freezed: ^0.14.0+1
  test: ^1.16.5
  very_good_analysis: ^2.0.0
