name: common_bloc
description: A collection of common blocs and cubits that maybe will be used very often (powered by the bloc library).
version: 4.1.1
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.3.0
  bloc: ^7.2.1
  dio: ^4.0.0
  freezed_annotation: ^0.14.3
  webfeed: ^0.7.0

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.2
  coverage: ^1.0.3
  freezed: ^0.14.5
  test: ^1.17.12
  very_good_analysis: ^2.3.0
