name: common_bloc
description: A collection of common blocs and cubits that maybe will be used very often (powered by the bloc library).
version: 4.1.0
homepage: https://github.com/pblinux/common_bloc
repository: https://github.com/pblinux/common_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  dio: ^4.0.0
  freezed_annotation: ^0.14.2
  webfeed: ^0.7.0

dev_dependencies:
  bloc_test: ^8.0.1
  build_runner: ^2.0.4
  coverage: ^1.0.3
  freezed: ^0.14.2
  test: ^1.17.5
  very_good_analysis: ^2.1.1
