name: common_bloc
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Testing
        run: |
          dart pub global activate coverage
          dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          exclude: "**/*.g.dart **/*.freezed.dart example/**"
          min_coverage: 95
          path: "./coverage/lcov.info"
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COVERAGE }}
  score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run:  flutter packages get
      - name: Install pana
        run:  flutter pub global activate pana
      - name: Check score
        run: |
          chmod +x ./scripts/score.sh
          ./scripts/score.sh
        shell: bash
