name: common_bloc
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: pub get
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Testing
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage    
      - name: Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          exclude: "**/*.g.dart **/*.freezed.dart example/**"
          min_coverage: 95
          path: "./coverage/lcov.info"
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COVERAGE }}
  score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: pub get
      - name: Install pana
        run: pub global activate pana
      - name: Check score
        run: ./score.sh
