name: common_bloc
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.12
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Format code
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Testing
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "**/*.g.dart **/*.freezed.dart example/**"
          min_coverage: 95
          path: "./coverage/lcov.info"
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COVERAGE }}